### ISSUE TITLE
Register this package on packagist

### ISSUE THREAD

**Issue by brunowego** [troglodyte/business-days#1]
To register this package you need change the name `BusinessDays` to `business-days`:

The package name troglodyte/BusinessDays is invalid, it should not contain uppercase characters. We suggest using troglodyte/business-days instead.

**Comment by brunowego** [comment]
Only need change the name on `composer.json` file. #2

**Comment by brunowego** [comment]
Only for work purpose, I registered this package on packagist, when you accept the pull request I will transfer for you: 

https://packagist.org/packages/troglodyte/business-days

**Comment by troglodyte** [comment]
Thanks brunowego - I did accept the pull request.

**Comment by brunowego** [comment]
@troglodyte you have account on packagist?

**Comment by troglodyte** [comment]
Just signed up - same name - troglodyte
Thanks!

**Comment by brunowego** [comment]
Done @troglodyte, please remove my access :+1:
